services:
  project-zomboid-server:
    image: guich2507/project-zomboid:latest
    container_name: project-zomboid-server
    restart: unless-stopped

    environment:
      # OBLIGATOIRE
      PZ_ADMIN_PASSWORD: ${PZ_ADMIN_PASSWORD}

      # OPTIONNEL
      PZ_SERVER_NAME: ${PZ_SERVER_NAME:-pzserver}
      STEAM_BETA_BRANCH: ${STEAM_BETA_BRANCH:-public}

    volumes:
      - /home/data/pzserver:/pz

    ports:
      - "${PZ_PORT_MAIN:-16261}:16261/udp"
      - "${PZ_PORT_PLAYERS:-16262}:16262/udp"
      - "${PZ_PORT_STEAM:-8766}:8766/udp"
